#!/bin/bash

IMAGE_DIR="/usr/local/share/relax"

get_random_image() {
    local images=("$IMAGE_DIR"/*)
    echo "${images[RANDOM % ${#images[@]}]}"
}

show_notification() {
    local image_path=$(get_random_image)
    notify-send -i "$image_path" "$1" "$2"
}

while true; do
    repetition_period=$(( RANDOM % 2400 + 1200 ))
    relax_time=$(( RANDOM % 300 + 60 ))

    show_notification "Время отдохнуть!" "Посмотрите на красивое место в течение ${relax_time} секунд"
    
    sleep $relax_time
    
    show_notification "Отдых завершен" "Следующий перерыв через $((repetition_period / 60)) минут"
    
    sleep $repetition_period
done
